services:
  db:
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - "127.0.0.1:5437:5432"
  elasticsearch:
    environment:
      - bootstrap.memory_lock=true
    ports:
      - "127.0.0.1:9200:9200"
  django:
    build:
      args:
        RUN_SCRIPT: "./deploy/docker/dev.sh"
      context: ./
      dockerfile: ./deploy/images/django.Dockerfile
    image: comses/catalog/dev:latest
    environment:
      DJANGO_SETTINGS_MODULE: 'catalog.settings.dev'
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5006:5006"
    volumes:
      - .:/code
