# Production inherits the staging topology but enables production settings.
services:
  django:
    environment:
      DJANGO_SETTINGS_MODULE: 'catalog.settings.prod'
  scheduler:
    environment:
      DJANGO_SETTINGS_MODULE: 'catalog.settings.prod'
